; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 11:11:17 GMT-0400 (Eastern Daylight Time)


; home Y
G91 ; relative positioning
var maxTravel = move.axes[1].max - move.axes[1].min + 5 ; calculate how far Y can travel plus 5mm
G1 H1 Y{-var.maxTravel} F600 ; coarse home in the -Y direction
G1 Y5 F6000 ; move back 5mm
G1 H1 Y{-var.maxTravel} F300 ; fine home in the -Y direction
G90 ; absolute positioning
