; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 11:11:17 GMT-0400 (Eastern Daylight Time)

; home X
G91 ; relative positioning
var maxTravel = move.axes[0].max - move.axes[0].min + 5 ; calculate how far X can travel plus 5mm
G1 H1 X{-var.maxTravel} F600 ; coarse home in the -X direction
G1 X5 F6000 ; move back 5mm
G1 H1 X{-var.maxTravel} F300 ; fine home in the -X direction
G90 ; absolute positioning
