; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 11:11:17 GMT-0400 (Eastern Daylight Time)

; home Z
G91 ; relative positioning
var maxTravel = move.axes[2].max - move.axes[2].min + 5 ; calculate how far Z can travel plus 5mm
G1 H1 Z{-var.maxTravel} F600 ; coarse home in the -Z direction
G1 Z5 F6000 ; move down 5mm
G1 H1 Z{-var.maxTravel} F300 ; fine home in the -Z direction
G90 ; absolute positioning
